apiVersion: v1
kind: Service
metadata:
  name: azmcpserver
  namespace: mcp-app
  labels:
    app: azmcpserver
spec:
  selector:
    app: azmcpserver
  ports:
  - name: http
    port: 8005
    targetPort: 8005
    protocol: TCP
  type: ClusterIP
