trigger:
  - main

variables:
  tag:  'latest'
  azmcpserverImage: 'eswarchivatam/azmcpserver:$(tag)'
  mcpclientImage:  'eswarchivatam/mcpclient:$(tag)'
  mcpfrontendImage: 'eswarchivatam/mcpfrontend:$(tag)'
  k8sNamespace: 'mcp-app'

stages:
- stage: KubernetesManifests
  displayName: Copy Manifests
  jobs:
  - job: KubernetesManifestsCopy
    displayName: Copy kubernetes manifests
    pool:
      name: default
    steps:
      - task: CopyFiles@2
        displayName: 'Copy Kubernetes Manifests'
        inputs:
          SourceFolder: '$(System.DefaultWorkingDirectory)'
          Contents: '**/*.yaml'
          TargetFolder: '$(Build.ArtifactStagingDirectory)/manifests'
      - task: PublishBuildArtifacts@1
        displayName: 'Publish Manifests'
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'manifests'
          publishLocation: 'Container'

- stage: Deploy
  displayName: Deploy image
  jobs:
  - job: Deploy
    displayName: Deploy
    pool:
      name: default
    steps:
    - task: DownloadPipelineArtifact@2
      displayName: 'Download Manifests'
      inputs:
        buildType: 'current'
        artifactName: 'manifests'
        itemPattern: '**/*.yaml'
        targetPath: '$(System.ArtifactsDirectory)'

    - task: AzureCLI@2
      displayName: 'Debug - List Downloaded Files'
      inputs:
        azureSubscription: 'kubernetes-service-connection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "Contents of $(System.ArtifactsDirectory):"
          ls -la "$(System.ArtifactsDirectory)"
          echo "Looking for manifests folder:"
          ls -la "$(System.ArtifactsDirectory)/manifests" || echo "manifests folder not found"

    - task: AzureCLI@2
      displayName: 'Create/Update Kubernetes Namespace and Secrets'
      inputs:
        azureSubscription: 'kubernetes-service-connection' # <-- Replace with your Azure Resource Manager connection name
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az aks command invoke \
            --resource-group MultiAgentDataVisual \
            --name Multiagent_AKS \
            --command "kubectl create namespace $(k8sNamespace) --dry-run=client -o yaml | kubectl apply -f -"
          az aks command invoke \
            --resource-group MultiAgentDataVisual \
            --name Multiagent_AKS \
            --command "kubectl create secret generic azure-sql-secret -n $(k8sNamespace) --from-literal=password=$AZURE_SQL_PASSWORD --dry-run=client -o yaml | kubectl apply -f -"
          az aks command invoke \
            --resource-group MultiAgentDataVisual \
            --name Multiagent_AKS \
            --command "kubectl create secret generic azure-openai-secret -n $(k8sNamespace) --from-literal=api-key=$AZURE_OPENAI_API_KEY --dry-run=client -o yaml | kubectl apply -f -"
      env:
        AZURE_SQL_PASSWORD: $(AZURE_SQL_PASSWORD)
        AZURE_OPENAI_API_KEY: $(AZURE_OPENAI_API_KEY)

    - task: AzureCLI@2
      displayName: 'Deploy azmcpserver'
      inputs:
        azureSubscription: 'kubernetes-service-connection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az aks command invoke \
            --resource-group MultiAgentDataVisual \
            --name Multiagent_AKS \
            --command "kubectl apply -f $(System.ArtifactsDirectory)/manifests/azmcpserver-deployment.yaml"
          az aks command invoke \
            --resource-group MultiAgentDataVisual \
            --name Multiagent_AKS \
            --command "kubectl apply -f $(System.ArtifactsDirectory)/manifests/azmcpserver-service.yaml"

    - task: AzureCLI@2
      displayName: 'Deploy mcp-client'
      inputs:
        azureSubscription: 'kubernetes-service-connection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az aks command invoke \
            --resource-group MultiAgentDataVisual \
            --name Multiagent_AKS \
            --command "kubectl apply -f $(System.ArtifactsDirectory)/manifests/mcp-client-deployment.yaml"
          az aks command invoke \
            --resource-group MultiAgentDataVisual \
            --name Multiagent_AKS \
            --command "kubectl apply -f $(System.ArtifactsDirectory)/manifests/mcp-client-service.yaml"

    - task: AzureCLI@2
      displayName: 'Deploy mcp-frontend'
      inputs:
        azureSubscription: 'kubernetes-service-connection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az aks command invoke \
            --resource-group MultiAgentDataVisual \
            --name Multiagent_AKS \
            --command "kubectl apply -f $(System.ArtifactsDirectory)/manifests/mcp-frontend-deployment.yaml"
          az aks command invoke \
            --resource-group MultiAgentDataVisual \
            --name Multiagent_AKS \
            --command "kubectl apply -f $(System.ArtifactsDirectory)/manifests/mcp-frontend-service.yaml"
