apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-frontend
  namespace: mcp-app
  labels:
    app: mcp-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-frontend
  template:
    metadata:
      labels:
        app: mcp-frontend
    spec:
      containers:
      - name: mcp-frontend
        image: mcp-frontend
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
