apiVersion: v1
kind: Service
metadata:
  name: rag-frontend-service
  namespace: rag-app
  labels:
    app: rag-frontend
spec:
  selector:
    app: rag-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
