apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: rag-app
  labels:
    app: rag-backend
spec:
  selector:
    app: rag-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
