apiVersion: v1
kind: Service
metadata:
  name: rag-backend-service
  namespace: rag-app
  labels:
    app: rag-backend
spec:
  selector:
    app: rag-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
