apiVersion: v1
kind: Secret
metadata:
  name: azure-sql-secret
  namespace: mcp-app
type: Opaque
data:
  password: eHh4eA==  # Base64 encoded "xxxx" - replace with your actual password
---
apiVersion: v1
kind: Secret
metadata:
  name: azure-openai-secret
  namespace: mcp-app
type: Opaque
data:
  api-key: eHh4eHg=  # Base64 encoded "xxxxx" - replace with your actual API key
